1. Scrape the details of most viewed videos on YouTube from Wikipedia. Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details: A) Rank B) Name C) Artist D) Upload date E) Views

In [4]:
import selenium
import time
import pandas as pd
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium import webdriver 
from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException,ElementNotVisibleException
import re

In [5]:
driver = webdriver.Chrome(r"C:\chromedriver.exe")

<ipython-input-5-e32e525e6bc1>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\chromedriver.exe")

In [6]:
driver.maximize_window()

In [7]:
driver.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')

In [8]:
try :
    tbody = driver.find_element(By.XPATH , '//*[@id="mw-content-text"]/div[1]/table[2]/tbody')
except NoSuchElementException:
    time.sleep(3)
    tbody = driver.find_element(By.XPATH , '//*[@id="mw-content-text"]/div[1]/table[2]/tbody')
    
try :
    ranking  = tbody.find_elements(By.XPATH , '//*[@id="mw-content-text"]/div[1]/table[2]/tbody//tr//td[@align="center"][1]')
    view = tbody.find_elements(By.XPATH , '//*[@id="mw-content-text"]/div[1]/table[2]/tbody//tr//td[@align="center"][2]')
    uploads = tbody.find_elements(By.XPATH , '//*[@id="mw-content-text"]/div[1]/table[2]/tbody//tr//td[@align="right"]')
except NoSuchElementException:
    time.sleep(3)
    ranking  = tbody.find_elements(By.XPATH , '//*[@id="mw-content-text"]/div[1]/table[2]/tbody//tr//td[@align="center"][1]')
    view = tbody.find_elements(By.XPATH , '//*[@id="mw-content-text"]/div[1]/table[2]/tbody//tr//td[@align="center"][2]')
    uploads = tbody.find_elements(By.XPATH , '//*[@id="mw-content-text"]/div[1]/table[2]/tbody//tr//td[@align="right"]')

In [9]:
rank = []
views = []
Name = []
Uploader = []
Date = []
    
for i in range(len(ranking)) :
    try :
        
        name  = driver.find_element(By.XPATH , '//*[@id="mw-content-text"]/div[1]/table[2]/tbody/tr['+str(i+1)+']/td[2]')
        uploader  = driver.find_element(By.XPATH , '//*[@id="mw-content-text"]/div[1]/table[2]/tbody/tr['+str(i+1)+']/td[3]')
        
    except NoSuchElementException:
        time.sleep(5)
        name  = driver.find_element(By.XPATH , '//*[@id="mw-content-text"]/div[1]/table[2]/tbody/tr['+str(i+1)+']/td[2]')
        uploader  = driver.find_element(By.XPATH , '//*[@id="mw-content-text"]/div[1]/table[2]/tbody/tr['+str(i+1)+']/td[3]')
            
    rank.append(ranking[i].text)
    views.append(view[i].text)
    Date.append(uploads[i].text)
    Name.append(name.text)
    Uploader.append(uploader.text)

In [10]:
df = pd.DataFrame({
    "Rank":rank,
    "Name":Name,
    "Uploader":Uploader,
    "Uploading_date":Date,
    "Views":views
})
df

,Rank,Name,Uploader,Uploading_date,Views
0,1.,"""Baby Shark Dance""[3]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",10.84
1,2.,"""Despacito""[6]",Luis Fonsi,"January 12, 2017",7.88
2,3.,"""Johny Johny Yes Papa""[12]",LooLoo Kids,"October 8, 2016",6.38
3,4.,"""Shape of You""[13]",Ed Sheeran,"January 30, 2017",5.75
4,5.,"""See You Again""[15]",Wiz Khalifa,"April 6, 2015",5.55
5,6.,"""Bath Song""[20]",Cocomelon – Nursery Rhymes,"May 2, 2018",5.46
6,7.,"""Phonics Song with Two Words""[21]",ChuChu TV,"March 6, 2014",4.69
7,8.,"""Uptown Funk""[22]",Mark Ronson,"November 19, 2014",4.60
8,9.,"""Learning Colors – Colorful Eggs on a Farm""[23]",Miroshka TV,"February 27, 2018",4.58
9,10.,"""Masha and the Bear – Recipe for Disaster""[24]",Get Movies,"January 31, 2012",4.50
10,11.,"""Gangnam Style""[25]",Psy,"July 15, 2012",4.46
11,12.,"""Wheels on the Bus""[30]",Cocomelon – Nursery Rhymes,"May 24, 2018",4.14
12,13.,"""Dame Tu Cosita""[31]",El Chombo,"April 5, 2018",3.96
13,14.,"""Sugar""[32]",Maroon 5,"January 14, 2015",3.71
14,15.,"""Roar""[33]",Katy Perry,"September 5, 2013",3.60
15,16.,"""Counting Stars""[34]",OneRepublic,"May 31, 2013",3.59
16,17.,"""Sorry""[35]",Justin Bieber,"October 22, 2015",3.56
17,18.,"""Thinking Out Loud""[36]",Ed Sheeran,"October 7, 2014",3.46
18,19.,"""Axel F""[37]",Crazy Frog,"June 16, 2009",3.40
19,20.,"""Girls Like You""[38]",Maroon 5,"May 31, 2018",3.30
20,21.,"""Faded""[39]",Alan Walker,"December 3, 2015",3.30
21,22.,"""Dark Horse""[40]",Katy Perry,"February 20, 2014",3.29
22,23.,"""Baa Baa Black Sheep""[41]",Cocomelon – Nursery Rhymes,"June 25, 2018",3.27
23,24.,"""Let Her Go""[42]",Passenger,"July 25, 2012",3.25
24,25.,"""Bailando""[43]",Enrique Iglesias,"April 11, 2014",3.22
25,26.,"""Lean On""[44]",Major Lazer,"March 22, 2015",3.22
26,27.,"""Perfect""[45]",Ed Sheeran,"November 9, 2017",3.19
27,28.,"""Shake It Off""[46]",Taylor Swift,"August 18, 2014",3.18
28,29.,"""Waka Waka (This Time for Africa)""[47]",Shakira,"June 4, 2010",3.17
29,30.,"""Mi Gente""[48]",J Balvin,"June 29, 2017",3.10

2. Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Match title (I.e. 1
st ODI)

B) Series
C) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [123]:
import selenium
import time
import pandas as pd
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium import webdriver 
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException,ElementNotVisibleException,ElementClickInterceptedException 
import re

In [124]:
driver = webdriver.Chrome(r"C:\chromedriver.exe")

<ipython-input-124-e32e525e6bc1>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\chromedriver.exe")

In [125]:
driver.maximize_window()

In [126]:
driver.get('https://www.bcci.tv')

In [127]:
driver.get(url)

In [ ]:
driver.maximize_window()
driver.get('https://www.bcci.tv')
try :
    international = driver.find_element(By.XPATH , '//*[@id="navigation"]/ul[1]/li[2]/a').click()
except NoSuchElementException:
    time.sleep(3)
    international = driver.find_element(By.XPATH , '//*[@id="navigation"]/ul[1]/li[2]/a').click()
    driver.get(international.get_attribute('href'))

driver.execute_script("arguments[0].click();", WebDriverWait(driver, 20).until(EC.element_to_be_clickable((By.XPATH, '//*[@id="fixtures"]/div[3]/div[2]/div/button'))))

team1  = driver.find_elements(By.XPATH , '//*[@class="match-country-info"][1]')
team2 = driver.find_elements(By.XPATH , '//*[@class="match-country-info"][2]')
data1 = driver.find_elements(By.XPATH , '//*[@class="fix-place ng-binding ng-scope"]')

date = []
Time = []
Series = []
Place = []
Match = []

for i in range(1,10):
    try:
        time.sleep(5)
        Date = driver.find_element(By.XPATH , '//*[@id="fixtures"]/div[3]/div/div['+str(i)+']/div/div[1]/div/div[1]/h5')
        timing = driver.find_element(By.XPATH , '//*[@id="fixtures"]/div[3]/div/div['+str(i)+']/div/div[1]/div/div[2]/h5')
    except NoSuchElementException:
        time.sleep(3)
        Date = driver.find_element(By.XPATH , '//*[@id="fixtures"]/div[3]/div/div['+str(i)+']/div/div[1]/div/div[1]/h5')
        timing = driver.find_element(By.XPATH , '//*[@id="fixtures"]/div[3]/div/div['+str(i)+']/div/div[1]/div/div[2]/h5')
        
    match = data1[i-1].text[:9]
    places = data1[i-1].text[10:]  
    series = team1[i-1].text + ' vs '+team2[i-1].text
    Series.append(series)
    Match.append(match)
    Place.append(places)
    date.append(Date.text)
    Time.append(timing.text)
    
#     print(Date.text , timing.text , series ,'--',places )
df  = pd.DataFrame({
    "Match":Match,
    "Series":Series,
    "Date":date,
    "Place":Place,
    "Time":Time
})
df

3. Scrape the details of selenium exception from guru99.com. Url = https://www.guru99.com/ You need to find following details: A) Name B) Description Note: - From guru99 home page you have to reach to selenium exception handling page through code

In [26]:
import selenium
import time
import pandas as pd
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium import webdriver 
from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException,ElementNotVisibleException
import re

In [27]:
driver = webdriver.Chrome(r"C:\chromedriver.exe")

<ipython-input-27-e32e525e6bc1>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\chromedriver.exe")

In [28]:
driver.maximize_window()

In [29]:
driver.get('https://www.guru99.com/')

In [30]:
try :
    selenium = WebDriverWait(driver, 2).until(EC.presence_of_element_located((By.XPATH, '//*[@id="java_technologies"]/li[3]/a')))
    selenium.click()
except:
    selenium = driver.find_element(By.XPATH , '//*[@id="java_technologies"]/li[3]/a').click()
try :
    selenium_exception = WebDriverWait(driver, 2).until(EC.presence_of_element_located((By.XPATH, '//*[@title="Selenium Exception Handling (Common Exceptions List)"]')))
    selenium_exception.click()
except:
    selenium_exception = driver.find_element(By.XPATH , '//*[@title="Selenium Exception Handling (Common Exceptions List)"]').click()

time.sleep(3)
name = driver.find_elements(By.XPATH , '//*[@id="post-1953"]/div/div/table/tbody//tr//td[1]')
description = driver.find_elements(By.XPATH , '//*[@id="post-1953"]/div/div/table/tbody//tr//td[2]')

In [31]:
Name = []
Description = []
for i in range(len(name)):
    Name.append(name[i].text)
    Description.append(description[i].text)

In [32]:
df = pd.DataFrame({
    "Name":Name,
    "Description":Description
})
df

,Name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

4. Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details:
A) Rank
B) State
C) GSDP(18-19)
D) GSDP(17-18)
E) Share(2017)
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code.

In [ ]:
import selenium
import time
import pandas as pd
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium import webdriver 
from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException,ElementNotVisibleException
import re

In [ ]:
driver = webdriver.Chrome(r"C:\chromedriver.exe")

In [ ]:
driver.maximize_window()

In [ ]:
driver.get(' http://statisticstimes.com/')

In [ ]:
Economy = driver.find_element(By.XPATH , '//*[@id="top"]/div[2]/div[2]/button').click()
try :
    india = driver.find_element(By.XPATH , '//*[@id="top"]/div[2]/div[2]//div//a[3]').click()
except:
    india = driver.find_element(By.XPATH , '//*[@id="top"]/div[2]/div[2]//div//a[3]')
    driver.get(india.get_attribute('href'))
time.sleep(10)

try:
    time.sleep(2)
    gdp1 = driver.find_element(By.XPATH , '/html/body/div[2]/div[2]/div[2]/ul/li[1]/a').click()
except:
    driver.get(gdp.get_attribute('href'))
    
try:
    rank = driver.find_elements(By.XPATH , '//*[@id="table_id"]/tbody//tr//td[1]')
    name = driver.find_elements(By.XPATH , '//*[@id="table_id"]/tbody//tr//td[2]')
    gsdp1 = driver.find_elements(By.XPATH , '//*[@id="table_id"]/tbody//tr//td[3]')
    gsdp2 = driver.find_elements(By.XPATH , '//*[@id="table_id"]/tbody//tr//td[4]')
    share = driver.find_elements(By.XPATH , '//*[@id="table_id"]/tbody//tr//td[5]')
    gdp = driver.find_elements(By.XPATH , '//*[@id="table_id"]/tbody//tr//td[6]')
except :
    time.sleep(5)
    rank = driver.find_elements(By.XPATH , '//*[@id="table_id"]/tbody//tr//td[1]')
    name = driver.find_elements(By.XPATH , '//*[@id="table_id"]/tbody//tr//td[2]')
    gsdp1 = driver.find_elements(By.XPATH , '//*[@id="table_id"]/tbody//tr//td[3]')
    gsdp2 = driver.find_elements(By.XPATH , '//*[@id="table_id"]/tbody//tr//td[4]')
    share = driver.find_elements(By.XPATH , '//*[@id="table_id"]/tbody//tr//td[5]')
    gdp = driver.find_elements(By.XPATH , '//*[@id="table_id"]/tbody//tr//td[6]')

In [ ]:
Rank  = []
Name = []
Gsdp1 = []
Gsdp2 = []
Share = []
Gdp = []

In [ ]:
for i in range(len(rank)) :
    Rank.append(rank[i].text) 
    Name.append(name[i].text)
    Gsdp1.append(gsdp1[i].text)
    Gsdp2.append(gsdp2[i].text)
    Share.append(share[i].text)
    Gdp.append(gdp[i].text)

In [ ]:
df = pd.DataFrame({
    "Rank":Rank,
    "Name":Name,
    "GSDP_19-20":Gsdp1,
    "GSDP_18-19":Gsdp2,
    "Share":Share,
    "GDP":Gdp
})
df

5. Scrape the details of trending repositories on Github.com. Url = https://github.com/ You have to find the following details: A) Repository title B) Repository description C) Contributors count D) Language used Note: - From the home page you have to click on the trending option from Explore menu through code

In [55]:
import selenium
import time
import pandas as pd
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium import webdriver 
from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException,ElementNotVisibleException
import re

In [56]:
driver = webdriver.Chrome(r"C:\chromedriver.exe")

<ipython-input-56-e32e525e6bc1>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\chromedriver.exe")

In [57]:
driver.maximize_window()
driver.get(' https://github.com/')

In [ ]:
try :
    time.sleep(2)
    explore = driver.find_element(By.XPATH , '/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary').click()
except:
    time.sleep(2)
    driver.get(explore.get_attribute('href'))
    
try :
    time.sleep(3)
    trending =  driver.find_element(By.XPATH , '//*[@href="/trending"]').click()
except:
    time.sleep(3)
    driver.get(trending.get_attribute('href'))
    
language = [] 
contributor = []
Name = []
Description = []
Pr_Languages = []
Contributor = []

In [ ]:
for i in range(1,26):
    name = driver.find_element(By.XPATH , '//*[@id="js-pjax-container"]/div[3]/div/div[2]/article['+str(i)+']//h1//a')
    desc = driver.find_element(By.XPATH , '//*[@id="js-pjax-container"]/div[3]/div/div[2]/article['+str(i)+']//p')
    Name.append(name.text)
    Description.append(desc.text)
    try :     
        lang = driver.find_element(By.XPATH , '//*[@id="js-pjax-container"]/div[3]/div/div[2]/article['+str(i)+']//div[@class="f6 color-fg-muted mt-2"]//span[@itemprop="programmingLanguage"]')
        language.append(lang.text)
    except:
        language.append('-')
    try :
        cont = driver.find_element(By.XPATH , '//*[@id="js-pjax-container"]/div[3]/div/div[2]/article['+str(i)+']/div[2]/a[2]')
        contributor.append(cont.text)
    except:
        contributor.append('-')
for j in range(len(language)):
    Pr_Languages.append(language[j])
    Contributor.append(contributor[j])

In [ ]:
df = pd.DataFrame({
    "Name":Name,
    "Description":Description,
    "Language" : Pr_Languages,
    "Contributor":Contributor
})
df

6. Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/ You have to find the following details: A) Song name B) Artist name C) Last week rank D) Peak rank E) Weeks on board Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [67]:
import selenium
import time
import pandas as pd
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium import webdriver 
from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException,ElementNotVisibleException
import re

In [68]:
driver = webdriver.Chrome(r"C:\chromedriver.exe")

<ipython-input-68-e32e525e6bc1>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\chromedriver.exe")

In [69]:
driver.maximize_window()

In [70]:
driver.get('https:/www.billboard.com/')

In [71]:
time.sleep(2)

In [72]:
try:
    hot = driver.find_element(By.XPATH , '//*[@id="main-wrapper"]/header/div[2]/div/nav/ul/li[1]/a').click()
except:
    driver.get(hot.get_attribute('href'))
time.sleep(4)
try:
    name = driver.find_elements(By.XPATH , '//*[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max"]//li[1]//h3')
    art = driver.find_elements(By.XPATH , '//*[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max"]//li[1]//span')
    last = driver.find_elements(By.XPATH , '//*[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max"]//li[@class="o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max"][1]//span')
    chart = driver.find_elements(By.XPATH , '//*[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max"]//li[@class="o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max"][2]')
    pos = driver.find_elements(By.XPATH , '//*[@class="o-chart-results-list__item // a-chart-bg-color a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-background-color-grey-lightest lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-hidden@mobile-max"][2]')
except :
    time.sleep(3)
    name = driver.find_elements(By.XPATH , '//*[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max"]//li[1]//h3')
    art = driver.find_elements(By.XPATH , '//*[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max"]//li[1]//span')
    last = driver.find_elements(By.XPATH , '//*[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max"]//li[@class="o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max"][1]//span')
    pos = driver.find_elements(By.XPATH , '//*[@class="o-chart-results-list__item // a-chart-bg-color a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-background-color-grey-lightest lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-hidden@mobile-max"][2]')
    chart = driver.find_elements(By.XPATH , '//*[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max"]//li[@class="o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max"][2]')

In [73]:
Name = []
Artist = []
Last_week = []
Peak = []
wks_chart = []
for i in range(len(name)):
    Name.append(name[i].text)
    Artist.append(art[i].text)

for j in range(len(last)):
    Last_week.append(last[j].text)
    Peak.append(pos[j].text)
    wks_chart.append(chart[j].text)
    
print(len(Name) , len(Artist),len(Last_week),len(Peak),len(wks_chart))

100 100 100 100 100

In [74]:
df = pd.DataFrame({
    "Name":Name,
    "Artist":Artist,
    "Last_week_rank":Last_week,
    "Peak_rank":Peak,
    "Weeks_on_Board":wks_chart
})
df

,Name,Artist,Last_week_rank,Peak_rank,Weeks_on_Board
0,As It Was,Harry Styles,1,1,11
1,First Class,Jack Harlow,2,1,10
2,Wait For U,Future Featuring Drake & Tems,3,1,7
3,About Damn Time,Lizzo,5,4,9
4,Running Up That Hill (A Deal With God),Kate Bush,4,4,23
...,...,...,...,...,...
95,Plan B,Megan Thee Stallion,95,29,4
96,Tomorrow Me,Luke Combs,-,61,2
97,Potion,"Calvin Harris, Dua Lipa & Young Thug",87,71,3
98,New Truck,Dylan Scott,-,99,1
99,Wrapped Around Your Finger,Post Malone,47,47,2

7. Scrape the details of Data science recruiters from naukri.com. Url = https://www.naukri.com/ You have to find the following details: A) Name B) Designation C) Company D) Skills they hire for E) Location Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and click on search. All this should be done through code

In [75]:
import selenium
import time
import pandas as pd
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium import webdriver 
from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException,ElementNotVisibleException
import re

In [76]:
driver = webdriver.Chrome(r"C:\chromedriver.exe")

<ipython-input-76-e32e525e6bc1>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\chromedriver.exe")

In [77]:
driver.maximize_window()

In [78]:
driver.get('https://www.naukri.com/hr-recruiters-consultants')

In [79]:
time.sleep(2)

In [80]:
input1 = driver.find_element(By.XPATH , '//*[@id="skill"]/div[1]/div[2]/input').send_keys('Data science')
time.sleep(2)
btn  = driver.find_element(By.XPATH , '//*[@id="qsbFormBtn"]').click()

try :
    name = driver.find_elements(By.XPATH , '//*[@class="fl ellipsis"]')
    desg = driver.find_elements(By.XPATH , '//*[@class="ellipsis clr"]')
    comp = driver.find_elements(By.XPATH , '//*[@class="recInfo"]//p//a[2]')
    skill = driver.find_elements(By.XPATH , '//*[@class="hireSec highlightable"]')
    
except :
    time.sleep(3)
    name = driver.find_elements(By.XPATH , '//*[@class="fl ellipsis"]')
    desg = driver.find_elements(By.XPATH , '//*[@class="ellipsis clr"]')
    comp = driver.find_elements(By.XPATH , '//*[@class="recInfo"]//p//a[2]')
    skill = driver.find_elements(By.XPATH , '//*[@class="hireSec highlightable"]')
Name = []
Designation = []
Company=[]
Location = []
Skills = []
link = driver.find_elements(By.XPATH,'//*[@class="outerRecSec"]//*[@class="recInfo"]//div[@class="vcard"]')
for i in range(len(link)):    
    a  = link[i].text.split('\n')
    if len(a)==4:    
        Location.append(a[-1])
    else:
        Location.append('-')
for i in range(len(name)):
    Name.append(name[i].text),
    Designation.append(desg[i].text)
    Company.append(comp[i].text)
    Skills.append(skill[i].text)

In [81]:
df = pd.DataFrame({
    "Name":Name,
    "Designation":Designation,
    "Company":Company,
    "Location":Location,
    "Skills":Skills
})
df

,Name,Designation,Company,Location,Skills
0,Aakash Harit,HR Manager,Data Science Network,Delhi,"Classic ASP Developer, Internet Marketing Prof..."
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,Hyderabad / Secunderabad,".Net, Java, Data Science, Linux Administration..."
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,Pune,"Data Science, Artificial Intelligence, Machine..."
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,Ahmedabad,"Mean Stack, javascript, angularjs, mongodb, We..."
4,subhas patel,Founder CEO,LibraryXProject,UK - (london),"Hadoop, Spark, Digital Strategy, Data Architec..."
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,Vadodara / Baroda,"Analytics, Business Intelligence, Business Ana..."
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Chennai,Data Science
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,Trivandrum,"Machine Learning, algorithms, Go Getter, Compu..."
8,Asif Lucknowi,Director,Weupskill- Live Wire India,Indore,"Technical Training, Software Development, Pres..."
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,Bengaluru / Bangalore,"Software Development, It Sales, Account Manage..."
10,Priyanka Akiri,HR Manager,Infinitive Software Solutions,Hyderabad,"Oracle Dba, Data Science, Data Warehousing, ET..."
11,Kalpana Dumpala,Executive Hiring,Innominds Software,Hyderabad / Secunderabad,"Qa, Ui/ux, Java Developer, Java Architect, C++..."
12,Mubarak,Company HR,MoneyTap,Bengaluru / Bangalore,"Business Intelligence, Data Warehousing, Data ..."
13,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,Mumbai,"Office Administration, Hr Administration, tele..."
14,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,Hyderabad / Secunderabad,"Social Media, digital media maketing, seo, smm..."
15,Kapil Devang,HR Manager,BISP Solutions,Bhopal,"Big Data, Hadoop, Data Analytics, Data Science"
16,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,Chandigarh,"React.js, Data Science, Java, Front End, Busin..."
17,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,Pune,"Qlikview, Qlik Sense, Microsoft Azure, Power B..."
18,Manisha Yadav,HR Executive,Easi Tax,Navi Mumbai,"Telecalling, Client Interaction, Marketing, Re..."
19,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Cochin,Data Science
20,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,Delhi,"Corporate Sales, Software Development, Softwar..."
21,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,Hyderabad / Secunderabad,"Data Analytics, Data Science, Machine Learning..."
22,Rithika dadwal,HR Recruiter,Affine Analytics,Pune,"Data Science, Machine Learning, Python, R, Dee..."
23,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,Pune,"Big Data, Data Science, Artificial Intelligenc..."
24,Shaun Rao,Manager Human Resources,Exela Technologies,Pune,"Java, Net, Angularjs, Hr, Infrastructure, Mana..."
25,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,Pune,"Data Science, Artificial Intelligence, Machine..."
26,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,Bengaluru / Bangalore,"Software Architecture, Vp Engineering, Product..."
27,kumar,Proprietor,trainin,Bengaluru / Bangalore,"Data Science, Hadoop, Rpas, Devops, Python, Aw..."
28,Sunil Vedula,CEO,Nanoprecise Sci Corp,-,"Signal Processing, Machine Learning, Neural Ne..."
29,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,Delhi,"Web Technologies, Project Management, Software..."
30,Dhruv Dev Dubey,Company Recruitment Head,Confidential,Bengaluru / Bangalore,"Server Administartion, Verilog, Vhdl, Digital ..."
31,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd",Mysoru / Mysore,"Data Analytics, Managed Services, Team Leading..."
32,Avodha,Business Development Associate,Nikitha Palaparthi,Hyderabad / Secunderabad,"Ethical Hacking, Security Operations Center, S..."
33,Priya Khare,Senior Manager,Independent Consultant,Bengaluru / Bangalore,"Data Science, Artificial Intelligence, analyti..."
34,Amit Sharma,Consultant,ASCO consulting,New Delhi,"Machine Learning, Artificial Intelligence, Dat..."
35,Kanan,senior technology instructor,NY INST,Chennai,"C, C++, Artificial Intelligence, Python, Php, ..."
36,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,Aligarh,"Relationship Management, Retail Sales, Private..."
37,Brad,"Manager, Technical Recruiting",O.C. Tanner,Salt Lake City,"Data Science, Software Engineering"
38,Rutuja Pawar,Technical Recruiter,Demand Matrix,Pune,"Data Science, Big Data Analytics, Digital Mark..."
39,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,Bengaluru / Bangalore,"Data Science, Recruitment, Salary"
40,Ankit Sinha,Head Analytics,Suntech Global,Mumbai,"B.Tech, Tableau, Statistics, R, Analytics, Tim..."
41,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,Indore,"Software Development, Business Intelligence, B..."
42,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,Bengaluru / Bangalore,"Data Science, Node.js, Angularjs"
43,Ashwini,Director Global Delivery,MRP Advisers,MYSORE,"Data Science, Media Marketing, Resource Planni..."
44,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,Hyderabad / Secunderabad,"Data Analysis, Learning, Data Science, Compute..."
45,Rajani Nagaraj,HR Manager,WildJasmine,Bengaluru / Bangalore,"Java, Hadoop, R, Machine Learning, Spark, Flum..."
46,ROHIT Kumar,Architect,LNT Private Limited,Mumbai,"Software Development, Core Java, Unit Testing,..."
47,Amir Chowdhury,Managing Partner,Granular.ai,-,"Machine Learning, Data Science, Product Manage..."
48,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,Hyderabad / Secunderabad,"Data Science, Machine Learning, Big Data Analy..."
49,Sunny Sharma,Managing Director - HR,Western Service Providers,Mumbai,"Software Professionals, Engineering, Technical..."

8. Scrape the details of Highest selling novels. Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/ You have to find the following details: A) Book name B) Author name C) Volumes sold D) Publisher E) Genre

In [83]:
import selenium
import time
import pandas as pd
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium import webdriver 
from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException,ElementNotVisibleException
import re

In [84]:
driver = webdriver.Chrome(r"C:\chromedriver.exe")

<ipython-input-84-e32e525e6bc1>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\chromedriver.exe")

In [85]:
driver.maximize_window()

In [86]:
driver.get('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare')

In [87]:
try :
    tbody = driver.find_elements(By.XPATH , '//*[@id="article-body-blocks"]/div/table/tbody//tr')
except:
    time.sleep(3)
    tbody = driver.find_elements(By.XPATH , '//*[@id="article-body-blocks"]/div/table/tbody//tr')
Book  = []
Author  = []
Volume  = []
Publish  = []
Gen  = []

In [88]:
for i in range(1,len(tbody)+1):
    Name = driver.find_element(By.XPATH , '/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr['+str(i)+']/td[2]')
    Book.append(Name.text)
    author = driver.find_element(By.XPATH , '/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr['+str(i)+']/td[3]')
    Author.append(author.text)
    volume = driver.find_element(By.XPATH , '/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr['+str(i)+']/td[4]')
    Volume.append(volume.text)
    publish = driver.find_element(By.XPATH , '/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr['+str(i)+']/td[5]')
    Publish.append(publish.text)
    gen = driver.find_element(By.XPATH , '/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr['+str(i)+']/td[6]')
    Gen.append(gen.text)

In [89]:
df = pd.DataFrame({
    "Book_Name":Book,
    "Author_Name":Author,
    "Volume_Sold":Volume,
    "Publisher":Publish,
    "Genre":Gen
})
df

,Book_Name,Author_Name,Volume_Sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

9. Scrape the details most watched tv series of all time from imdb.com. Url = https://www.imdb.com/list/ls095964455/ You have to find the following details: A) Name B) Year span C) Genre D) Run time E) Ratings F) Votes

In [90]:
import selenium
import time
import pandas as pd
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium import webdriver 
from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException,ElementNotVisibleException
import re

In [91]:
driver = webdriver.Chrome(r"C:\chromedriver.exe")

<ipython-input-91-e32e525e6bc1>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\chromedriver.exe")

In [92]:
driver.maximize_window()

In [93]:
driver.get('https://www.imdb.com/list/ls095964455/')

In [94]:
try :
    name =  driver.find_elements(By.XPATH , '//*[@class="lister-item-header"]//a')
    year =  driver.find_elements(By.XPATH , '//*[@class="lister-item-year text-muted unbold"]')
    run =  driver.find_elements(By.XPATH , '//*[@class="runtime"]')
    gen =  driver.find_elements(By.XPATH , '//*[@class="genre"]')
    vote = driver.find_elements(By.XPATH , '//*[@class="genre"]')
except ElementNotVisibleException:
    time.sleep(3)
    name =  driver.find_elements(By.XPATH , '//*[@class="lister-item-header"]//a')
    year =  driver.find_elements(By.XPATH , '//*[@class="lister-item-year text-muted unbold"]')
    run =  driver.find_elements(By.XPATH , '//*[@class="runtime"]')
    gen =  driver.find_elements(By.XPATH , '//*[@class="genre"]')
    vote = driver.find_elements(By.XPATH , '//*[@class="genre"]')
Name = []
Year = []
Run = []
Gen = []
Vote = []
Rat = []

In [95]:
for i in range(len(name)):
    rat = driver.find_element(By.XPATH , '//*[@id="main"]/div/div[3]/div[3]/div['+str(i+1)+']/div[2]/div[1]/div[1]/span[2]')
    Name.append(name[i].text)
    Year.append(year[i].text)
    Run.append(run[i].text)
    Gen.append(gen[i].text)
    Vote.append(vote[i].text)
    Rat.append(rat.text)

In [96]:
df = pd.DataFrame({
    "Name":Name,
    "Year":Year,
    "Rating":Rat,
    "Run_Time":Run,
    "Genre":Gen,
    "Vote":Vote  
}) 
df

,Name,Year,Rating,Run_Time,Genre,Vote
0,Game of Thrones,(2011–2019),9.2,57 min,"Action, Adventure, Drama","Action, Adventure, Drama"
1,Stranger Things,(2016– ),8.7,51 min,"Drama, Fantasy, Horror","Drama, Fantasy, Horror"
2,The Walking Dead,(2010–2022),8.2,44 min,"Drama, Horror, Thriller","Drama, Horror, Thriller"
3,13 Reasons Why,(2017–2020),7.5,60 min,"Drama, Mystery, Thriller","Drama, Mystery, Thriller"
4,The 100,(2014–2020),7.6,43 min,"Drama, Mystery, Sci-Fi","Drama, Mystery, Sci-Fi"
...,...,...,...,...,...,...
95,Reign,(2013–2017),7.4,42 min,"Drama, Fantasy","Drama, Fantasy"
96,A Series of Unfortunate Events,(2017–2019),7.8,50 min,"Adventure, Comedy, Drama","Adventure, Comedy, Drama"
97,Criminal Minds,(2005–2020),8.1,42 min,"Crime, Drama, Mystery","Crime, Drama, Mystery"
98,Scream: The TV Series,(2015–2019),7.1,45 min,"Comedy, Crime, Drama","Comedy, Crime, Drama"
99,The Haunting of Hill House,(2018),8.6,572 min,"Drama, Horror, Mystery","Drama, Horror, Mystery"

10. Details of Datasets from UCI machine learning repositories. Url = https://archive.ics.uci.edu/ You have to find the following details: A) Dataset name B) Data type C) Task D) Attribute type E) No of instances F) No of attribute G) Year Note: - from the home page you have to go to the ShowAllDataset page through code.

In [101]:
import selenium
import time
import pandas as pd
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium import webdriver 
from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException,ElementNotVisibleException
import re

In [102]:
driver = webdriver.Chrome(r"C:\chromedriver.exe")

<ipython-input-102-e32e525e6bc1>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\chromedriver.exe")

In [103]:
driver.maximize_window()

In [104]:
driver.get('https://archive.ics.uci.edu/')

In [105]:
try : 
    view_data =  driver.find_element(By.XPATH , '/html/body/table[2]/tbody/tr/td/span/b/a').click()
except ElementNotVisibleException:
    time.sleep()
    view_data =  driver.find_element(By.XPATH , '/html/body/table[2]/tbody/tr/td/span/b/a')
    driver.get(view_data.get_attribute('href'))
try : 
    tbody =  driver.find_elements(By.XPATH , '/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody//tr[1]')
except ElementNotVisibleException:
    time.sleep()
    tbody =  driver.find_elements(By.XPATH , '/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody//tr[1]')

In [106]:
Name = []
Data_type = []
Task = []
Attr_type = []
Instance = []
Attr_sum = []
Year = []

In [107]:
for i in range(2,len(tbody)+1):
    try:
        name = driver.find_element(By.XPATH , '/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr['+str(i)+']/td[1]/table/tbody/tr/td[2]/p')
        data_type =  driver.find_element(By.XPATH , '/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr['+str(i)+']/td[2]')
        task =  driver.find_element(By.XPATH , '/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr['+str(i)+']/td[3]')
        attr_type =  driver.find_element(By.XPATH , '/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr['+str(i)+']/td[4]')
        instance =  driver.find_element(By.XPATH , '/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr['+str(i)+']/td[5]')
        attr_sum =  driver.find_element(By.XPATH , '/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr['+str(i)+']/td[6]')
        year =  driver.find_element(By.XPATH , '/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr['+str(i)+']/td[7]')
    except NoSuchElementException: # just for checking
        name = driver.find_element(By.XPATH , '/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr['+str(i)+']/td[1]/table/tbody/tr/td[2]/p')
        data_type =  driver.find_element(By.XPATH , '/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[623]/td[2]')
        task =  driver.find_element(By.XPATH , '/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[623]/td[3]')
        attr_type =  driver.find_element(By.XPATH , '/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[623]/td[4]')
        instance =  driver.find_element(By.XPATH , '/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[623]/td[5]')
        attr_sum =  driver.find_element(By.XPATH , '/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[623]/td[6]')
        year =  driver.find_element(By.XPATH , '/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[623]/td[7]')
        
    Name.append(name.text)
    Data_type.append(data_type.text)
    Task.append(task.text)
    Attr_type.append(attr_type.text)
    Instance.append(instance.text)
    Attr_sum.append(attr_sum.text)
    Year.append(year.text)

In [108]:
df = pd.DataFrame({
    "Name":Name,
    "Data_Type":Data_type,
    "Task":Task,
    "Attribute_Type":Attr_type,
    "Instance":Instance,
    "No._Attributes":Attr_sum,
    "Year":Year
})
df

,Name,Data_Type,Task,Attribute_Type,Instance,No._Attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021